name: Raising JIRA issues for Dependabot alerts

on:
  schedule:
    - cron: '0 0 1 * *'  
  workflow_dispatch:

jobs:
  syncSecurityAlerts:
    runs-on: ubuntu-latest
    steps:
      - name: "Sync security alerts to Jira issues"
        uses: reload/github-security-jira@v1.5.0
        env:
          GH_SECURITY_TOKEN: ${{ secrets.GitHubSecurityToken }}
          JIRA_TOKEN: ${{ secrets.JiraApiToken }}
          JIRA_HOST: https://83bb-182-72-16-113.ngrok-free.app
          JIRA_USER: ${{ secrets.UserId }}
          JIRA_PROJECT: SM
          JIRA_ISSUE_TYPE: Bug
